# Generated by Django 3.1.3 on 2020-11-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20201112_1108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
