# Generated by Django 3.1.3 on 2020-11-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20201112_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selsls',
            fields=[
                ('pro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='general.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.seller')),
            ],
        ),
    ]
