# Generated by Django 3.1.3 on 2020-11-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_selsls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selsls',
        ),
    ]
